=head1 NAME

B<random-password> - generate an ASCII random password

=head1 SYNOPSIS

B<random-password> [B<-h>] [B<-dulp>] I<length>


    random-password [-h] [-dulp] <length>

=head1 DESCRIPTION

Generates an ASCII random password.  It takes any combination of the B<-d>,
B<-u>, B<-l> and B<-p> options.  If none is given, assumes B<-dulp>.

=head1 OPTIONS

=over

=item -d

Allow decimal digits (0-9).

=item -u

Allow upper-case letters (A-Z).

=item -l

Allow lower-case letters (a-z).

=item -p

Allow ASCII punctuation.

=item B<-h>

Print a help message to standard error.

=back

=head1 EXIT CODE

=over

=item Z<>0

on success

=item Z<>2

on misuse or help request (B<-h>)

=item >0

on error

=back

=head1 EXAMPLES

Generate an alphanumeric password of length 20:

  random-password -dul 20

=head1 AUTHOR

Giuseppe Calabrese (contact@giucal.it)
